version: '1'
services:
  server:
    build: ./ # see Dockerfile
    volumes:
      - ./:/var/www/html
    ports:
      - 5001:80
      - 5002:443
  composer:
    image: "composer"
    volumes:
      - ./:/app
    command: composer update
  gotenberg:
    image: "gotenberg/gotenberg:8"
    ports:
      - 3000:3000
  db:
    image: "mysql"
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: prp
      MYSQL_USER: prp
      MYSQL_PASSWORD: prp
      MYSQL_ROOT_PASSWORD: root